"""
Reading and writing the bot's `key = value` config files.

Editing keeps everything the user wrote: comments, blank lines, unknown keys and
the line-ending style. Only the lines of the keys being changed are touched.
The bot's own parser applies the *last* occurrence of a key, so that is the one
we read and replace.
"""

import os
import re
import tempfile
from pathlib import Path

from schema import CATEGORIES, FIELDS

_ENTRY = re.compile(r"^(\s*)([A-Za-z0-9_.]+)\s*=\s?(.*?)\s*$")
_ADDED_MARKER = "# Added by the web interface"


def _is_entry(line):
    stripped = line.lstrip()
    return bool(stripped) and stripped[0] not in "#;" and not stripped.startswith("//")


def parse(text):
    """Return (lines, index) where index maps key -> list of line numbers of active entries."""
    lines = text.splitlines()
    index = {}
    for number, line in enumerate(lines):
        if _is_entry(line):
            match = _ENTRY.match(line)
            if match:
                index.setdefault(match.group(2), []).append(number)
    return lines, index


def read_values(text):
    """Effective values as the bot sees them (last occurrence wins)."""
    lines, index = parse(text)
    return {key: _ENTRY.match(lines[numbers[-1]]).group(3) for key, numbers in index.items()}


def apply_changes(text, changes):
    """
    Return `text` with `changes` (key -> value) applied.

    A value of None or "" removes the setting: its active lines are commented
    out, which restores the bot's default while keeping what the user had.
    """
    newline = "\r\n" if "\r\n" in text else "\n"
    lines, index = parse(text)
    appended = []

    for key, value in changes.items():
        numbers = index.get(key, [])
        if value in (None, ""):
            for number in numbers:
                lines[number] = "# " + lines[number].lstrip()
            continue
        if numbers:
            last = numbers[-1]
            indent = _ENTRY.match(lines[last]).group(1)
            lines[last] = f"{indent}{key} = {value}"
        else:
            appended.append(f"{key} = {value}")

    if appended:
        if lines and lines[-1].strip():
            lines.append("")
        if _ADDED_MARKER not in lines:
            lines.append(_ADDED_MARKER)
        lines.extend(appended)

    return newline.join(lines) + newline


def render_new(values):
    """Full config file for a new account, grouped by category with explanations."""
    out = ["# Lords Mobile Bot configuration",
           "# Generated by the web interface. Edit it there, or by hand.", ""]
    for category in CATEGORIES:
        out.append(f"# --- {category['label']} " + "-" * max(4, 60 - len(category["label"])))
        for field in category["fields"]:
            value = values.get(field["key"], field["default"])
            if field["type"] != "bool" and field.get("help"):
                out.append("# " + field["help"])
            if value == "":  # the bot's parser rejects an empty value, so leave the key out
                out.append(f"# {field['key']} =")
            else:
                out.append(f"{field['key']} = {value}")
        out.append("")
    return "\n".join(out)


def read_file(path):
    with open(path, "r", encoding="utf-8", newline="") as f:
        return f.read()


def write_private(path, text, keep_backup=True):
    """Atomic write, readable by the owner only. The previous version is kept as .bak."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if keep_backup and path.exists():
        backup = path.with_suffix(path.suffix + ".bak")
        backup.write_bytes(path.read_bytes())
        _chmod_private(backup)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=path.name + ".", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="") as f:
            f.write(text)
        _chmod_private(tmp)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def _chmod_private(path):
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass  # not supported on every filesystem (e.g. Windows drives mounted in WSL)


def extra_keys(text):
    """Active keys of the file that the web interface has no field for."""
    return {k: v for k, v in read_values(text).items() if k not in FIELDS}
