#ifndef BUILDING_TABLE_H
#define BUILDING_TABLE_H

/* The game's own building tables (types, per-level cost/duration/prerequisites), generated by
 * tools/extract_game_tables.py into src/building_table.c. Levels are the ones the server sends
 * (buildings.h): 1 to 25, then the mana levels up to 55; the Mana Lode and the Mana Chamber start at 25.
 * What is confirmed and how the tables were found: docs/buildings.md. */

#include <stdint.h>
#include <stddef.h>

#define BUILDING_REQ_MAX 9   // the most buildings one level asks for (the Academy)

typedef struct {
    uint32_t time;                  // base duration in seconds, before any speed bonus
    uint32_t cost[8];               // food, stone, wood, ore, gold, mana ore, mana crystal, manasteel
    uint8_t  req_id[BUILDING_REQ_MAX];     // a building of that type must be at req_level (0 = none)
    uint8_t  req_level[BUILDING_REQ_MAX];
    uint16_t research_id;           // a research at research_level (0 = none)
    uint8_t  research_level;
    uint16_t quest;                 // a step of the game's own quests (0 = none): not visible to the bot
} BuildingLevelInfo;

typedef struct {
    uint16_t    id;                 // build_id, as _MSG_RESP_BUILDINGINFO sends it
    uint8_t     kind;               // 0 general, 1 resource, 2 military, 3 familiar, 4 and 5 special (residence, towers)
    uint8_t     min_level;
    uint8_t     max_level;
    uint8_t     upgradeable;
    uint16_t    first_row;          // its min_level in BUILDING_LEVELS, then one row per level up to max_level
    const char *name_fr;
    const char *name_en;
} BuildingTypeInfo;

extern const BuildingTypeInfo  BUILDING_TYPES[];
extern const uint16_t          BUILDING_TYPE_COUNT;
extern const BuildingLevelInfo BUILDING_LEVELS[];

/* NULL for an id that is not a building of the table. */
static inline const BuildingTypeInfo *BuildingType(uint16_t id)
{
    for (uint16_t i = 0; i < BUILDING_TYPE_COUNT; i++)
        if (BUILDING_TYPES[i].id == id)
            return &BUILDING_TYPES[i];
    return NULL;
}

/* The row for reaching `level` of a building, NULL outside min_level..max_level. */
static inline const BuildingLevelInfo *BuildingLevelRow(const BuildingTypeInfo *t, uint8_t level)
{
    return (t && level >= t->min_level && level <= t->max_level) ? &BUILDING_LEVELS[t->first_row + (level - t->min_level)] : NULL;
}

/* Types the automatic construction can work on: upgradeable, more than one level, and not one of the special kinds. */
static inline int BuildingSelectable(const BuildingTypeInfo *t)
{
    return t && t->upgradeable && t->max_level > t->min_level && t->kind <= 3 && t->name_en && t->name_en[0];
}

#endif
