#ifndef RESEARCH_TABLE_H
#define RESEARCH_TABLE_H

/* The game's own research tables (categories, researches, per-level cost/duration/prerequisites),
 * generated by tools/extract_game_tables.py into src/research_table.c. Not read from the network:
 * the server only sends levels, by id (research.h). Ids are 1..RESEARCH_TECH_COUNT with no gap.
 * What is confirmed and how the tables were found: docs/research.md. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#define RESEARCH_KIND_COUNT_MAX 32 // room for the categories the game may add

typedef struct {
    uint8_t     kind;      // the game's category number, as RESEARCH_TECHS[].kind refers to it (not contiguous)
    uint8_t     order;     // position in the game's tabs, 1..16
    uint8_t     academy;   // Academy level the category needs
    const char *name_fr;
    const char *name_en;
} ResearchKindInfo;

typedef struct {
    uint32_t time;         // base duration in seconds, before any research-speed bonus
    uint32_t cost[5];      // food, stone, wood, ore, gold
    uint8_t  academy;      // Academy level this level needs
    uint16_t req_id[4];    // researches that must already be at req_level (0 = none)
    uint8_t  req_level[4];
} ResearchLevelInfo;

typedef struct {
    uint16_t    id;
    uint8_t     kind;
    uint8_t     max_level;
    uint8_t     locked;    // the game marks it not researchable the normal way
    uint16_t    first_row; // its level 1 in RESEARCH_LEVELS, then one row per level up to max_level
    const char *name_fr;
    const char *name_en;   // falls back to the French name when the English strings lack it
    const char *label_en;  // "Category: Name", for logs
} ResearchTechInfo;

extern const ResearchKindInfo  RESEARCH_KINDS[];
extern const uint16_t          RESEARCH_KIND_COUNT;
extern const ResearchLevelInfo RESEARCH_LEVELS[];
extern const ResearchTechInfo  RESEARCH_TECHS[];
extern const uint16_t          RESEARCH_TECH_COUNT;

/* NULL for an id outside the table. */
static inline const ResearchTechInfo *ResearchTech(uint16_t id)
{
    return (id >= 1 && id <= RESEARCH_TECH_COUNT) ? &RESEARCH_TECHS[id - 1] : NULL;
}

static inline const ResearchKindInfo *ResearchKind(uint8_t kind)
{
    for (uint16_t i = 0; i < RESEARCH_KIND_COUNT; i++)
        if (RESEARCH_KINDS[i].kind == kind)
            return &RESEARCH_KINDS[i];
    return NULL;
}

/* The row for reaching `level` (1..max_level) of a research, NULL otherwise. */
static inline const ResearchLevelInfo *ResearchLevelRow(const ResearchTechInfo *t, uint8_t level)
{
    return (t && level >= 1 && level <= t->max_level) ? &RESEARCH_LEVELS[t->first_row + level - 1] : NULL;
}

#endif
