/* GENERATED by tools/extract_game_tables.py from the game's own Soldier table - do not edit by hand. */
#ifndef TROOP_TABLE_H
#define TROOP_TABLE_H

#include <stdint.h>

/* What ONE troop costs before any bonus: [TroopKind][tier T1..T4] = food, stone, wood, ore, gold, seconds.
 * Bonuses (research, VIP...) only lower it, so what this says a stock can pay for is a floor. T5 is not made from
 * resources, it is not in the table. */
static const uint16_t TROOP_COST[4][4][6] = {
	{
		{ 50, 0, 50, 50, 0, 15 },
		{ 100, 0, 100, 100, 5, 30 },
		{ 150, 0, 150, 150, 10, 60 },
		{ 1000, 0, 1000, 1000, 500, 120 },
	},
	{
		{ 50, 50, 50, 0, 0, 15 },
		{ 100, 100, 100, 0, 5, 30 },
		{ 150, 150, 150, 0, 10, 60 },
		{ 1000, 1000, 1000, 0, 500, 120 },
	},
	{
		{ 50, 50, 0, 50, 0, 15 },
		{ 100, 100, 0, 100, 5, 30 },
		{ 150, 150, 0, 150, 10, 60 },
		{ 1000, 1000, 0, 1000, 500, 120 },
	},
	{
		{ 50, 50, 50, 50, 0, 15 },
		{ 100, 100, 100, 100, 5, 30 },
		{ 150, 150, 150, 150, 10, 60 },
		{ 1000, 1000, 1000, 1000, 500, 120 },
	},
};

#endif
